import Head from "next/head";
import flagsmith from 'flagsmith/isomorphic';
import { useFlags, useFlagsmith } from 'flagsmith/react';

import { api } from "~/utils/api";

export default function Home() {

  const flags = useFlags(["test_feat_1", "test_feat_2"]);
  const test_feat_1 = flags.test_feat_1
  const test_feat_2 = flags.test_feat_2
  console.log("test_feat_1", test_feat_1);

  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex flex-col gap-10 text-white text-5xl">
          <div className="text-7xl">Status</div>
          <div>
            <div >Test Feature 1</div>
            <div className="text-3xl">Status | isOn: <span className="uppercase">{`${test_feat_1.enabled}`}</span></div>
          </div>
          <div>
            <div >Test Feature 2</div>
            <div className="text-3xl">Status | isOn: <span className="uppercase">{`${test_feat_2.enabled}`}</span></div>
          </div>
        </div>
      </main>
    </>
  );
}
